#!/bin/bash
# Regenerate shell completions for netspeed-cli

set -e

echo "Generating shell completions..."

# Build the project first
cargo build

# Completions will be generated by build.rs
echo "Completions generated in completions/"
echo "Man page generated: netspeed-cli.1"

# Show generated files
ls -la completions/
ls -la netspeed-cli.1
